
try {
    var a = 5
    var b = "hola"
    console.log("antes del calculo");
    
    console.log(a/c);
    console.log("Final del programa");
} catch (e) {
    console.log("ocurrio un error de calculo");    
}finally{
    console.log("siempre se ejecuta");    
}
console.log("fuera del try");



